sample: sample.cpp
	g++ sample.cpp -o sample -lglut -lGLU -lGL
sampleLarge: sampleLarge.cpp
	g++ sampleLarge.cpp -o sampleLarge -lglut -lGLU -lGL
maze: maze.cpp
	g++ maze.cpp -o maze -lglut -lGLU -lGL
